name: Kick

on:
  workflow_run:
    workflows: [Success-jobs]
    types: [completed]

jobs:
  success-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run:  |
          echo 'Worked upon job completion!'
          echo '${{ toJSON(github.event.workflow_run) }}'